name: Daily Telegram post

on:
  schedule:
    # GitHub Actions работает по UTC
    # Москва 21:23 (UTC+3) → 18:23 UTC
    - cron: "23 18 * * *"
  workflow_dispatch: {}  # возможность запустить вручную

jobs:
  post_and_delete:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        id: send
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          POST_TEXT: ${{ secrets.POST_TEXT }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          RESP=$(curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\":\"${CHANNEL_ID}\",\"text\":\"${POST_TEXT}\",\"disable_web_page_preview\":false,\"disable_notification\":true}")
          echo "Response: $RESP"
          MSG_ID=$(echo "$RESP" | jq -r '.result.message_id')
          if [ "$MSG_ID" = "null" ] || [ -z "$MSG_ID" ]; then echo "Failed"; exit 1; fi
          echo "message_id=$MSG_ID" >> $GITHUB_OUTPUT

      - name: Wait before delete
        run: |
          SECS=${{ secrets.DELETE_AFTER_SECONDS }}
          if [ -z "$SECS" ]; then SECS=60; fi
          echo "Sleeping ${SECS}s"
          sleep "$SECS"

      - name: Delete message
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MSG_ID: ${{ steps.send.outputs.message_id }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/deleteMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\":\"${CHANNEL_ID}\",\"message_id\":${MSG_ID}}"
